import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const myFont = localFont({
  src: "../../fonts/GeneralSans-Variable.ttf",
  variable: "--font-generalSans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${myFont.variable} font-sans justify-center items-center flex`}
    >
      <body suppressHydrationWarning={true} className="bg-red-500">
        <Navbar />
        <main className="w-full max-w-[1440px] bg-white">
          <div className="mx-auto w-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
